name: Black Duck SCA Scan with SARIF Generation
                                                                                                                                                                                                                                          
on:
  push:
    branches: [ main, master, develop, stage, release ]
  
                                                                                                                                                                                                                                          
jobs:
  blackducksca-sarif-report:
    runs-on: [mac-arm-sh]
                                                                                                                                                                                                                                          
    defaults:
      run:
        working-directory: ${{ github.workspace }}/nodejs-npm

    steps:
    - name: Checkout Source
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'  # Specify Node version
   
    - name: Install dependencies
      run: npm install  

    - name: Build Project
      run: |
        npm rebuild

    - name: Black Duck SCA Scan with SARIF Generation
      uses: blackduck-inc/black-duck-security-scan@v2
      with:
        blackducksca_url: ${{ secrets.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        blackducksca_reports_sarif_create: true
        blackducksca_reports_sarif_severities: 'CRITICAL,HIGH'
        blackducksca_reports_sarif_groupSCAIssues: false
        detect_args: "--detect.source.path=${{ github.workspace }}/nodejs-npm"
        blackducksca_upload_sarif_report: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
